name: lsa-sd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=13.2.0.2
  - libgomp=13.2.0.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libwinpthread=9.0.0.6454.b4445ee52.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.3.0
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.12.3
  - python-dateutil=2.9.0
  - python_abi=3.12
  - pywin32=306
  - pyzmq=26.0.3
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - accelerate==0.31.0.dev0
      - addict==2.4.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - diffusers==0.27.2
      - filelock==3.14.0
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - groundingdino-py==0.4.0
      - huggingface-hub==0.23.0
      - idna==3.7
      - intel-openmp==2021.4.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mkl==2021.4.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - pillow==10.3.0
      - pycocotools==2.0.7
      - pyparsing==3.1.2
      - pyyaml==6.0.1
      - regex==2024.4.28
      - requests==2.31.0
      - safetensors==0.4.3
      - segment-anything==1.0
      - supervision==0.6.0
      - sympy==1.12
      - tbb==2021.12.0
      - timm==0.9.16
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.3.0+cu121
      - torchaudio==2.3.0+cu121
      - torchvision==0.18.0
      - tqdm==4.66.4
      - transformers==4.40.2
      - urllib3==2.2.1
      - windows-curses==2.3.2
      - yapf==0.40.2
